version: 1
update_configs:
  - package_manager: rust:cargo
    directory: /
    update_schedule: weekly
    default_labels:
      - dependencies
      - dependabot
      - rust
  - package_manager: github_actions
    directory: /
    update_schedule: weekly
    default_labels:
      - dependabot
      - github-actions
